# -*- coding: utf-8 -*-
"""Product Review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1koUJ7AQ2Gx_-opBgpoG6oRbCR2QT-Ct7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

uploaded = files.upload()

print(uploaded.keys())

import zipfile

with zipfile.ZipFile("Dataset-SA.csv.zip", "r") as zip_ref:
    zip_ref.extractall("dataset")

print("ZIP extracted successfully!")

import os

print(os.listdir("dataset"))

import pandas as pd

df = pd.read_csv("dataset/Dataset-SA.csv")

print("Dataset loaded successfully!")
print(df.head())

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print(df.columns)

df.info()

print(df.isnull().sum())

print("Duplicate rows:", df.duplicated().sum())

print(df.describe())

print(df["Sentiment"].value_counts())

print(df["Rate"].value_counts().sort_index())

print(df[["Review", "Summary", "Sentiment"]].head(10))

df.columns = df.columns.str.strip()

print(df.columns)

print(df.isnull().sum())

df = df.dropna(subset=["Review", "Summary", "Sentiment"])

print("After removing missing values:", df.shape)

df = df.drop_duplicates()

print("After removing duplicates:", df.shape)

print(df.dtypes)

df["Rate"] = pd.to_numeric(df["Rate"], errors="coerce")

print(df["Rate"].dtype)

print(df["Sentiment"].value_counts())

df["Review"] = df["Review"].astype(str).str.strip()
df["Summary"] = df["Summary"].astype(str).str.strip()
df["Sentiment"] = df["Sentiment"].astype(str).str.strip()

print(df[["Review", "Summary", "Sentiment"]].head())

df["Sentiment"] = df["Sentiment"].str.capitalize()

print(df["Sentiment"].value_counts())

print(df.isnull().sum())

print("Cleaned Dataset Shape:", df.shape)
print(df.head())

df.to_csv("cleaned_product_reviews.csv", index=False)

print("Cleaned dataset saved successfully!")

print("Mean Rate:", df["Rate"].mean())

print("Median Rate:", df["Rate"].median())

print("Mode Rate:", df["Rate"].mode()[0])

print("Minimum Rate:", df["Rate"].min())
print("Maximum Rate:", df["Rate"].max())

rate_range = df["Rate"].max() - df["Rate"].min()

print("Range:", rate_range)

print("Variance:", df["Rate"].var())

print("Standard Deviation:", df["Rate"].std())

print("===== Statistical Analysis =====")

print("Mean:", df["Rate"].mean())
print("Median:", df["Rate"].median())
print("Mode:", df["Rate"].mode()[0])
print("Minimum:", df["Rate"].min())
print("Maximum:", df["Rate"].max())
print("Range:", df["Rate"].max() - df["Rate"].min())
print("Variance:", df["Rate"].var())
print("Standard Deviation:", df["Rate"].std())

print(df.groupby("Sentiment")["Rate"].mean())

print("Total Reviews:", len(df))
print("Average Rating:", df["Rate"].mean())
print("Highest Rating:", df["Rate"].max())
print("Lowest Rating:", df["Rate"].min())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))

plt.hist(df["Rate"], bins=5)

plt.title("Distribution of Product Ratings")
plt.xlabel("Rating")
plt.ylabel("Number of Reviews")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x=df["Rate"])

plt.title("Box Plot of Product Ratings")
plt.xlabel("Rating")

plt.show()

plt.figure(figsize=(8,5))

df["Sentiment"].value_counts().plot(kind="bar")

plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")
plt.xticks(rotation=0)

plt.show()

print(df.columns.tolist())

plt.figure(figsize=(8,5))

plt.hist(df["Rate"], bins=5)

plt.title("Distribution of Product Ratings")
plt.xlabel("Rating")
plt.ylabel("Number of Reviews")

plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x=df["Rate"])

plt.title("Box Plot of Product Ratings")
plt.xlabel("Rating")

plt.show()

plt.figure(figsize=(8,5))

df["Sentiment"].value_counts().plot(kind="bar")

plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")
plt.xticks(rotation=0)

plt.show()

avg_rating = df.groupby("Sentiment")["Rate"].mean()

print(avg_rating)

plt.figure(figsize=(8,5))

avg_rating.plot(kind="bar")

plt.title("Average Rating by Sentiment")
plt.xlabel("Sentiment")
plt.ylabel("Average Rating")
plt.xticks(rotation=0)

plt.show()

sentiment_count = df["Sentiment"].value_counts()

print(sentiment_count)

print("===== OBSERVATIONS =====")

print("1. The histogram shows the distribution of customer ratings.")

print("2. The box plot shows the spread and possible outliers in ratings.")

print("3. The bar chart shows the number of Positive, Negative and Neutral reviews.")

print("4. Average rating by sentiment helps compare customer opinions.")

print("5. Sentiment and rating can be used to understand customer satisfaction.")

print(df["Review"].head(10))

df["Review_Clean"] = df["Review"].astype(str).str.lower()

print(df[["Review", "Review_Clean"]].head())

import re

def clean_text(text):
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

df["Review_Clean"] = df["Review_Clean"].apply(clean_text)

print(df[["Review", "Review_Clean"]].head())

print(df["Sentiment"].value_counts())

sentiment_mapping = {
    "Positive": 1,
    "Neutral": 0,
    "Negative": -1
}

df["Sentiment_Label"] = df["Sentiment"].map(sentiment_mapping)

print(df[["Sentiment", "Sentiment_Label"]].head(10))

print(df["Sentiment_Label"].isnull().sum())

print(df[["Review_Clean", "Sentiment", "Sentiment_Label"]].head(10))
print(df.shape)

df.to_csv("preprocessed_product_reviews.csv", index=False)

print("Preprocessed dataset saved successfully!")

